/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hPNEV3fG1Ek
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Link from "next/link"

export function Post() {
  return (
    (<Card className="w-full max-w-md rounded-lg overflow-hidden shadow-lg">
      <div className="relative">
        <img
          src="/placeholder.svg"
          width={600}
          height={600}
          alt="Post Image"
          className="w-full h-[400px] object-cover"
          style={{ aspectRatio: "600/600", objectFit: "cover" }} />
        <div
          className="absolute top-4 right-4 bg-primary text-primary-foreground px-3 py-1 rounded-md text-sm font-medium">
          Featured
        </div>
      </div>
      <CardFooter className="p-6 bg-background">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div>
              <Link href="#" className="font-medium text-lg" prefetch={false}>
                shadcn
              </Link>
              <div className="text-sm text-muted-foreground">@shadcn · 2h ago</div>
            </div>
          </div>
          <div className="flex items-center gap-3 text-muted-foreground">
            <HeartIcon className="w-6 h-6" />
            <span className="text-lg font-medium">1.2K</span>
          </div>
        </div>
        <div className="text-base leading-relaxed">
          <Link href="#" className="font-medium text-lg" prefetch={false}>
            shadcn
          </Link>
          This is a beautiful photo I took on my recent trip to the mountains. The scenery was breathtaking!
        </div>
      </CardFooter>
    </Card>)
  );
}

function HeartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>)
  );
}
